---

- name: Download and unarchive nodeexporter
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
    dest: "{{ dest_folder }}"
    remote_src: yes

- name: Start nodeexporter
  command: "{{ dest_folder }}/node_exporter-1.3.1.linux-amd64/node_exporter"
  async: 1000
  poll: 0
